apiVersion: v1
kind: Service
metadata:
  name: java-report-core
  namespace: default
  creationTimestamp: "2000-01-01T00:00:00Z"
  resourceVersion: "1"
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
