import test from 'node:test';
import assert from 'node:assert/strict';

import {
  buildSmokeJwt,
  buildCreateTaskRequest,
  buildConfirmOutlineRequest,
  buildModelInvocationSql,
  evaluateSmokeResult,
  extractReportSummary,
} from '../../../scripts/uc01-real-provider-smoke-lib.mjs';

function decodeJwtPayload(token) {
  const [, payload] = token.split('.');
  return JSON.parse(Buffer.from(payload, 'base64url').toString('utf8'));
}

test('buildSmokeJwt creates a signed HS256 JWT with a two hour expiry window', () => {
  const before = Math.floor(Date.now() / 1000);
  const token = buildSmokeJwt({
    secret: 'unit-test-secret',
    payload: {
      sub: '1',
      roles: ['ADMIN'],
      permissions: ['report:create', 'report:read'],
      status: 'enabled',
    },
  });
  const parts = token.split('.');
  assert.equal(parts.length, 3);

  const header = JSON.parse(Buffer.from(parts[0], 'base64url').toString('utf8'));
  const payload = decodeJwtPayload(token);
  assert.deepEqual(header, { alg: 'HS256', typ: 'JWT' });
  assert.equal(payload.sub, '1');
  assert.deepEqual(payload.roles, ['ADMIN']);
  assert.deepEqual(payload.permissions, ['report:create', 'report:read']);
  assert.equal(payload.status, 'enabled');
  assert.ok(payload.iat >= before);
  assert.ok(payload.exp - payload.iat === 7200);
});

test('buildCreateTaskRequest and buildConfirmOutlineRequest produce the UC-01 smoke payloads', () => {
  const topic = 'UC01 real provider smoke 1712345678901';
  assert.deepEqual(buildCreateTaskRequest(topic), {
    topic,
    payload: {
      acceptance: 'UC-01-real-provider',
    },
  });

  assert.deepEqual(buildConfirmOutlineRequest(), {
    outline: ['执行摘要', '关键发现'],
    confirmed: true,
  });
});

test('buildModelInvocationSql targets the task audit evidence needed by UC-01 smoke', () => {
  assert.equal(
    buildModelInvocationSql(207),
    'select task_id, provider, model_name, status, total_tokens, trace_id from model_invocations where task_id = 207 order by id desc limit 1;',
  );
});

test('extractReportSummary reads completed report evidence from API payload', () => {
  const summary = extractReportSummary({
    data: {
      reportId: 335,
      currentVersionId: 127,
      status: 'completed',
      sections: [
        {
          title: 'Executive summary',
          content: 'Generated by real provider.',
          citations: [{ referenceId: 77 }],
        },
      ],
    },
  });

  assert.deepEqual(summary, {
    reportId: 335,
    status: 'completed',
    currentVersionId: 127,
    sectionCount: 1,
    citationCount: 1,
  });
});

test('evaluateSmokeResult passes in strict mode when completed report and real provider audit both exist', () => {
  assert.deepEqual(
    evaluateSmokeResult({
      strictAudit: true,
      reportSummary: { status: 'completed' },
      modelInvocation: {
        provider: 'openai-compatible',
        modelName: 'qwen-plus',
        status: 'succeeded',
      },
    }),
    [],
  );
});

test('evaluateSmokeResult fails in strict mode when audit evidence is missing or fallback is used', () => {
  assert.deepEqual(
    evaluateSmokeResult({
      strictAudit: true,
      reportSummary: { status: 'completed' },
      modelInvocation: null,
    }),
    ['STRICT_AUDIT_REQUIRES_MODEL_INVOCATION'],
  );

  assert.deepEqual(
    evaluateSmokeResult({
      strictAudit: true,
      reportSummary: { status: 'completed' },
      modelInvocation: {
        provider: 'local-fallback',
        modelName: 'local-rag-fallback',
        status: 'succeeded',
      },
    }),
    ['STRICT_AUDIT_REQUIRES_REAL_PROVIDER'],
  );
});
