ALTER TABLE rule_approval_records
    ADD COLUMN IF NOT EXISTS sla_hours INTEGER,
    ADD COLUMN IF NOT EXISTS remind_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_reminded_at TIMESTAMP WITH TIME ZONE;
