apiVersion: v1
kind: Endpoints
metadata:
  name: java-report-core
  namespace: default
  creationTimestamp: "2000-01-01T00:00:00Z"
  resourceVersion: "1"
subsets:
- addresses:
  - ip: 172.30.0.2
  ports:
  - name: http
    port: 8080
    protocol: TCP
