apiVersion: v1
data:
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIF+zCCA+OgAwIBAgIUKC1e1WXUMH+/LH5NlvgiMQre9DswDQYJKoZIhvcNAQEL
    BQAwgYsxCzAJBgNVBAYTAkNOMREwDwYDVQQIDAhTaGFuZ2hhaTERMA8GA1UEBwwI
    U2hhbmdoYWkxEDAOBgNVBAoMB0hpZ3Jlc3MxEDAOBgNVBAsMB0dhdGV3YXkxEDAO
    BgNVBAMMB1Jvb3QgQ0ExIDAeBgkqhkiG9w0BCQEWEXJvb3RjYUBoaWdyZXNzLmlv
    MCAXDTI2MDYyMzA3NDUxNFoYDzIxMjYwNTMwMDc0NTE0WjCBizELMAkGA1UEBhMC
    Q04xETAPBgNVBAgMCFNoYW5naGFpMREwDwYDVQQHDAhTaGFuZ2hhaTEQMA4GA1UE
    CgwHSGlncmVzczEQMA4GA1UECwwHR2F0ZXdheTEQMA4GA1UEAwwHUm9vdCBDQTEg
    MB4GCSqGSIb3DQEJARYRcm9vdGNhQGhpZ3Jlc3MuaW8wggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCm6BVtTcaEh6J6Vup4P+0aAWlyK4AQJAaqpPnp1O9b
    A0xKRS1+fxdWzFbVJYbW29AeVDJ16YdEVOkL75+RkrYITLTPDM0hLViMLOoi3jZX
    J3Cx8aYmgpSx9FzafWxaVpKFlRroq2fyMJFDKYzstPtDEc413c/ubOMad2kqjU01
    MTUbVEpwMeRJY1YsC/bMf6tVgXqlUgKyliWuUdIFfhUoMFlD9CDYSiBYVF3jaU0Q
    IUaGvvptN3cn2JNqqKg6RaLMpIbBrXxe9eZ8WERX9jgSbEEjEdZwy8qGfhacFcnp
    rC2IlbecptKPy/iEC0yxcN52h89TZRLj0RKjjhHomFMMoUa1nSc4QXPJxel9aQrF
    D2f49BB/ISV/CQLgtW9fxTqwFMA0NCuS+d7nSHlcWl1LEFs86zYgft9JD1HFkWvp
    UDkCCIh28BqNc819gBsr0Ju6hNTdZU/PUY064RYLG3gl2e+W+TkXsbkGL602io+c
    1y3v5i6Ano2FxCumaYyfIv4DYDOXZFr2HNPKGEvxWabymQAn6PqL7dBWmqp5G65P
    e9FnuCZCtBHdrUf+itlT32l/CsFmBdjM6xsR+RrNe0dtozJb2i7Fh6wTvrf5af9M
    8gWrCyx01XvSFsRJx+WTUlIt3QLzZZDVQy++zPHjZs3laSvuH7UVydc/j5LQE8aE
    fQIDAQABo1MwUTAdBgNVHQ4EFgQUri2v/QjxHnO5825LWP62cgoe1DUwHwYDVR0j
    BBgwFoAUri2v/QjxHnO5825LWP62cgoe1DUwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAgEALZVaj4UTVHbI+g8cBkzBtfb0oHHIhTVuUXBpJBifIwqq
    XIkF2191NWL7a1GmD5XB4+Dq2a3iQgTauc7PwIhcGTbY56r9wJmy1PzkQwWnBCp+
    IE9ihCe5QMPofc6jSIFNq4RTkxfU03In0uJrtpnBttlvHL0q0TRYqJcPqtPcvfAq
    I/eLqtPiZG6QH0Xp/jJGvCxg9iTP0uAURbbUQaKKbgABCIrfck2mIJGXlF7cIPlJ
    WQ8j7oTUR4O+Kez4Qd1uCuASUup+MoNTgxfa1VFE7ip5BrDtjti10E0w88j0QoPf
    YhF79uSWexbTeoaFS2awuth8YhAjvCVvu/gjXS2vYF5jIqtBI6jL0PTqPzAOUSh9
    TEac2zfk5FBOy9VRPL+8Q0fgrA1nCBl0CCo/LB4dqFWocqKFkFnTua0+NLALpYqe
    TPu3N8rOzQeplk28AuwQKnT1rWN+v/GV/HUz29fdm8q4i/eKkGv1XWp/PuOo2FYA
    vlgbyFYce4vm7gbxbZ7b/NhwqMgn9ifp+PVF/tyB5GC1+arYrf0NTzfyhBWUGSMC
    6QnK9+QtKE3u6NpQv3cQW8AWDlxJfLqnAmFOpowCkWTrUFtFG3FUF3suGT5UZ/jZ
    smHP7DeAW4sAO1LutDJhNy/zrU/6XduXF71cnA80DwBWU11T6mqUirx4MRMET3Y=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-23T00:52:50Z"
  labels:
    istio.io/config: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:root-cert.pem: {}
      f:metadata:
        f:labels:
          .: {}
          f:istio.io/config: {}
    manager: pilot-discovery
    operation: Update
    time: "2026-06-23T07:45:28Z"
  name: higress-ca-root-cert
  namespace: higress-system
  resourceVersion: "2"
