apiVersion: v1
data:
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIF+zCCA+OgAwIBAgIUCzkQA3cj0poN85p1wgX55srJCu0wDQYJKoZIhvcNAQEL
    BQAwgYsxCzAJBgNVBAYTAkNOMREwDwYDVQQIDAhTaGFuZ2hhaTERMA8GA1UEBwwI
    U2hhbmdoYWkxEDAOBgNVBAoMB0hpZ3Jlc3MxEDAOBgNVBAsMB0dhdGV3YXkxEDAO
    BgNVBAMMB1Jvb3QgQ0ExIDAeBgkqhkiG9w0BCQEWEXJvb3RjYUBoaWdyZXNzLmlv
    MCAXDTI2MDcwODA5MTYzM1oYDzIxMjYwNjE0MDkxNjMzWjCBizELMAkGA1UEBhMC
    Q04xETAPBgNVBAgMCFNoYW5naGFpMREwDwYDVQQHDAhTaGFuZ2hhaTEQMA4GA1UE
    CgwHSGlncmVzczEQMA4GA1UECwwHR2F0ZXdheTEQMA4GA1UEAwwHUm9vdCBDQTEg
    MB4GCSqGSIb3DQEJARYRcm9vdGNhQGhpZ3Jlc3MuaW8wggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCVN83Yj8t/jjK2rVPma8InOLJ9TNGuh2yOMU6jIOvG
    eO2wfc05M2q1U4wtxx/u1jTblvXVJEOBG6ncKmlfrA5sJmv7mrznH8O38ahS2uNU
    h6pwkQaqhWoD6j8sm6OreeTGsi2dfwCgjNohjdqr45XGGOgXPXYx4P3dncMHmlLV
    x0kcGYsYKqWYQGMky6ELHvzendqRNN627HHCFLtr498QGFFBqIOkJeXaKyuY/3D2
    L6e1ljkHsMUEmijoSISz2KwJUupMba69LfPgK9ArTKviLWlukSAk4UsEgpMhf1QW
    VpkfPYQcOZHy3TFh9NPMk+W2GBX8qCnfm7YWXw8JvYo93CbGhrEEjsvzVznl7jbN
    weGhxS1ZV+D1EduLgCS6tRwxcDXO3IiYpOuZf0kypN6Qjh7iHb5v9lcl1XyxV+kz
    iWXykBcHkLXXBWZOD+P9TUkSvXwM0XE5/oLHEv+n8BbxYonf+q+bJuYeCFklqvrM
    mxjFKmkdzTu+jOQeBIelkuB1/F8bD8uhf9SZxkwYXNCynRx0W/gxkkNu8AZGbnde
    J5TJHpeHNdHzZQibLlukAuTb4Cdf1im7bIaCvuFxPVh+wUyso9e/v+4MKDRVgryw
    Nv9QQ/2JtbvGS6ZEVUU4chzm0Tyf2JjClHjZ0MGU7e7kWCGgJ1IfXpQBCxxdPxxK
    6QIDAQABo1MwUTAdBgNVHQ4EFgQU2o82e2bOlUdH84H5KzSu/MGBlQIwHwYDVR0j
    BBgwFoAU2o82e2bOlUdH84H5KzSu/MGBlQIwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAgEAkBe6zaIlb1r+9wLzX2TYqSURGiszr+BiWhh9aGo9Fpwx
    UayNpLhrZXb9hhqyCs/s/+n8utn1YuLW/AtjjfLh+/nX2yDOWYpAlZi5YkzYnHIv
    1A9DV0J6SXpjBVCwhAz6yO6tuqpDT2xWAgtcw/R1LpGaTvwcGBZLDPUI5HMwokKj
    9aDawY09mjiM7/TCbgKKk3zcU4gR8rI06pc9FEbpdLy9uMlCsG7s3btd+ZRQx8VI
    jw6cB1fSq0Cf5nloGvjUVFHew4K5pT9BlZIlGexYLG+a9/M9Eya3FfJCF2TTgDBr
    yGqWVji+MwiUHgpIrrODZEdaV3498LoMFiJyNjhwRFncTkpF1BI5D8pj1+KGtc+h
    slE2LnUMl0hB9IU/GEYypqWk3rpInDlf3Q6okUbggMKqqRVKo771HKMUT88MQaLI
    mZusitLNq0RwTZkFHkFEc8l7SL85LhduwhtnxBF3djvXLH1dLs9xsCKTPEZU+KLd
    xGlQWPE89IVHiydpfh+t6gNBHkJscT/xdksVF6MCLwfc7LBg3jhmjR11kUt5Qj/i
    wx9AaDfhtuMYiPigZ9TehrDW6Xi5pR3kovCOIe0Ve963BjF1sidOeUgxutFMoIwe
    NgFgATOBDhYkLhCGg08Y48iRn8TAhNIvMSaJTxsH4yHG/NPnzVWvGNZheiosd20=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-23T00:52:50Z"
  labels:
    istio.io/config: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:root-cert.pem: {}
      f:metadata:
        f:labels:
          .: {}
          f:istio.io/config: {}
    manager: pilot-discovery
    operation: Update
    time: "2026-07-08T09:16:47Z"
  name: higress-ca-root-cert
  namespace: higress-system
  resourceVersion: "81"
